dashboard/urls.py
from django.urls import path

from .views import (
    dashboard,
    products,
    glasses,
    glasses_detail,
    create_glasses,
    delete_glasses,
    frames_detail,
    create_frame,
    frames,
    outlets,
    subcats,
    create_subcat,
    delete_subcat,
    subcat_detail
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('products/subcategories/', subcats, name='subcats'),
    path('products/subcategories/create/', create_subcat, name='subcat_create'),
    path('products/subcategories/<int:pk>/', delete_subcat, name='subcat_delete'),
    path('products/subcategories/detail/<int:pk>/', subcat_detail, name='subcat_detail'),

    path('products/', products, name='products'),
    path('products/glasses/', glasses, name='glasses'),
    path('products/glasses/detail/<int:pk>/', glasses_detail, name='glasses_detail'),
    path('products/glasses/create/', create_glasses, name='glasses_create'),
    path('products/delete/<int:pk>/', delete_glasses, name='glasses_delete'),

    path('products/frames/', frames, name='frames'),
    path('products/frames/detail/<int:pk>/', frames_detail, name='frame_detail'),
    path('products/frames/create/', create_frame, name='frame_create'),

    path('products/outlets/', outlets, name='outlets'),



]

optic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/', include('filters.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include([
        path('events/', include('events.urls')),
        path('products/', include('products.urls')),
    ])),
    path('', include('orders.urls')),
    path('', include('contacts.urls')),


    path('', TemplateView.as_view(template_name='index.html')),
    path('cart', TemplateView.as_view(template_name='index.html')),
    path('aboutUs', TemplateView.as_view(template_name='index.html')),
    path('salon', TemplateView.as_view(template_name='index.html')),
    path('delivery', TemplateView.as_view(template_name='index.html')),
    path('product/<id>', TemplateView.as_view(template_name='index.html')),
    path('event/<id>', TemplateView.as_view(template_name='index.html')),
    path('cart/order', TemplateView.as_view(template_name='index.html')),
    path('product/<cat>/<subcat>', TemplateView.as_view(template_name='index.html')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include

from .api import (
    VolumesList,
    MaterialsList,
    ProductsList,
    BrandsList,
    RadiusesList,
    OpticalPowersList,
    SubCategoriesList,
    ProductDetail,
    ProductsCartList
)



urlpatterns = [
    path('list/', ProductsList.as_view()),
    path('cart/list/', ProductsCartList.as_view()),
    path('detail/<int:pk>/', ProductDetail.as_view()),
    path('subcategories/', SubCategoriesList.as_view()),


    # FILTER
    path('volumes/', VolumesList.as_view()),
    path('materials/', MaterialsList.as_view()),
    path('brands/', BrandsList.as_view()),
    path('radiuses/', RadiusesList.as_view()),
    path('opt_powers/', OpticalPowersList.as_view()),

]

products/models.py
from django.db import models
import uuid
import os

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('products_images', filename)

from .validators import min_0

CATEGORIES = (
    ('glasses', 'glasses'),
    ('frames', 'frames'),
    ('outlet', 'outlet'),
)


class SubCategory(models.Model):
    value = models.CharField(max_length=20)
    cat = models.CharField(max_length=20, choices=CATEGORIES)

    def __str__(self):
        return self.value

class Brand(models.Model):
    value = models.CharField(max_length=100)
    def __str__(self):
        return self.value

    class Meta:
        ordering = ('value',)

class Material(models.Model):
    value = models.CharField(max_length=100)
    def __str__(self):
        return self.value
    class Meta:
        ordering = ('value',)

class Radius(models.Model):
    value = models.CharField(max_length=100)
    def __str__(self):
        return self.value
    class Meta:
        ordering = ('value',)

class OpticalPower(models.Model):
    value = models.CharField(max_length=100)
    def __str__(self):
        return self.value
    class Meta:
        ordering = ('value',)

class Volume(models.Model):
    value = models.CharField(max_length=100)
    def __str__(self):
        return self.value
    class Meta:
        ordering = ('value',)

class Product(models.Model):
    ''' Products model '''

    SEXES = (
        ('man', 'man'),
        ('woman', 'woman'),
        ('unisex', 'unisex'),
        ('child', 'child'),
    )

    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField(default=0)

    img_1 = models.ImageField(upload_to=get_file_path, null=True, blank=True)
    img_2 = models.ImageField(upload_to=get_file_path, null=True, blank=True)
    img_3 = models.ImageField(upload_to=get_file_path, null=True, blank=True)

    cat = models.CharField(max_length=10, choices=CATEGORIES)
    subcat = models.ForeignKey(SubCategory, blank=True, null=True, on_delete=models.SET_NULL)

    is_new = models.BooleanField(default=True)
    is_leader = models.BooleanField(default=False)
    is_discount = models.BooleanField(default=False)
    discount = models.IntegerField(validators=[min_0], null=True, default=0)


    # GLASSES
    brand = models.ForeignKey(Brand, blank=True, null=True, on_delete=models.SET_NULL)
    material = models.ForeignKey(Material, blank=True, null=True, on_delete=models.SET_NULL)
    sex = models.CharField(max_length=20, choices=SEXES, null=True, blank=True)

    #FRAMES
    radius = models.ForeignKey(Radius, blank=True, null=True, on_delete=models.SET_NULL)
    opt_power = models.ForeignKey(OpticalPower, blank=True, null=True, on_delete=models.SET_NULL)


    #KAPLI
    volume = models.ForeignKey(Volume, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ('title', 'price',)

    def __str__(self):
        return "{} | {} | {} T".format(self.title, self.cat, self.price)

    def get_max_price(self):
        return max([i.price for i in self.objects.all()])

    def get_min_price(self):
        return min([i.price for i in self.objects.all()])

dashboard/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
# from django.contrib import messages

from products.forms import GlassesForm, FramesForm, SubcatForm
from products.models import Product, SubCategory


@login_required(login_url='login')
@staff_member_required(login_url='login')
def dashboard(request):
    return redirect('products')


def delete_null():
    for product in Product.objects.all():
        if len(product.title) == 0:
            product.delete()


@login_required(login_url='login')
@staff_member_required(login_url='login')
def products(request):
    delete_null()
    products = Product.objects.all()
    subcategories = SubCategory.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search', None)
        products = products.filter(title__contains=search)

    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'subcategories': subcategories,
        'title': 'ВСЕ ПРОДУКТЫ'
    }
    return render(request, 'dashboard/products/products.html', context)

@login_required(login_url='login')
@staff_member_required(login_url='login')
def glasses(request):
    products = Product.objects.filter(cat='glasses')
    subcategories = SubCategory.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search', None)
        products = products.filter(title__contains=search)


    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'subcategories': subcategories,
        'title': 'ОЧКИ'
    }
    return render(request, 'dashboard/products/products.html', context)

@login_required(login_url='login')
@staff_member_required(login_url='login')
def outlets(request):
    products = Product.objects.filter(cat='outlet')
    subcategories = SubCategory.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search', None)
        products = products.filter(title__contains=search)


    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'subcategories': subcategories,
        'title': 'OUTLETS'
    }
    return render(request, 'dashboard/products/products.html', context)

@login_required(login_url='login')
@staff_member_required(login_url='login')
def frames(request):
    products = Product.objects.filter(cat='frames')
    subcategories = SubCategory.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search', None)
        products = products.filter(title__contains=search)


    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'products': page_obj,
        'subcategories': subcategories,
        'title': 'Линзы'
    }
    return render(request, 'dashboard/products/products.html', context)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def create_glasses(request):
    product = Product(cat='glasses')
    product.save()
    return redirect('glasses_detail', pk=product.id)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def create_frame(request):
    product = Product(cat='frames')
    product.save()
    return redirect('frame_detail', pk=product.id)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def glasses_detail(request, pk=None):
    product = Product.objects.get(id=pk)
    form = GlassesForm(instance=product, cat=product.cat)
    if request.method == 'POST':
        print(request.FILES)
        print(request.POST)
        form = GlassesForm(request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products')
    context = {
        'form':form,
        'product': product,
    }
    return render(request, 'dashboard/products/detail.html', context)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def frames_detail(request, pk=None):
    product = Product.objects.get(id=pk)
    form = FramesForm(instance=product, cat=product.cat)
    if request.method == 'POST':
        print(request.POST)
        form = GlassesForm(request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products')
    context = {
        'form':form,
        'product': product,
    }

    return render(request, 'dashboard/products/detail.html', context)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def delete_glasses(request, pk=None):
    item = Product.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('products')
    context = {
        'item': item.title
    }
    return render(request, 'dashboard/products/delete.html', context)



@login_required(login_url='login')
@staff_member_required(login_url='login')
def create_subcat(request):
    form = SubcatForm()


    if request.method == 'POST':
        form = SubcatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('subcats')

    context = {
        'form': form,
    }
    return render(request, 'dashboard/subcats/create.html', context)

@login_required(login_url='login')
@staff_member_required(login_url='login')
def subcats(request):
    subcats = SubCategory.objects.all()

    if request.method == 'POST':
        search = request.POST.get('search', None)
        subcats = subcats.filter(value__contains=search)



    context = {
        'subcats': subcats,
        'title': 'Субкатегории'
    }
    return render(request, 'dashboard/subcats/subcats.html', context)

@login_required(login_url='login')
@staff_member_required(login_url='login')
def delete_subcat(request, pk=None):
    item = SubCategory.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('products')
    context = {
        'item': item.value
    }
    return render(request, 'dashboard/subcats/delete.html', context)


@login_required(login_url='login')
@staff_member_required(login_url='login')
def subcat_detail(request, pk=None):
    subcat = SubCategory.objects.get(id=pk)
    form = SubcatForm(instance=subcat)
    if request.method == 'POST':
        form = SubcatForm(request.POST, instance=subcat)
        if form.is_valid():
            form.save()
            return redirect('subcats')
    context = {
        'form':form,
        'subcat': subcat,
    }

    return render(request, 'dashboard/subcats/detail.html', context)

dashboard/templates/dashboard/products/create.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block content %}
    <div class="container p-5 content-block">
    <a href="{% url 'products' %}" class="btn btn-primary m-3">Назад</a>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>

    </div>
{% endblock %}

dashboard/templates/dashboard/products/delete.html
{% extends 'dashboard/base.html' %}
{% load static %}


{% block content %}
    <div class="container p-5 content-block">
        <h3>Вы уверены что хотите удалить {{ item }}?</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <a class="btn btn-success" href="{% url 'products' %}">Нет</a>
            <input class="btn btn-danger" type="submit" name="Confirm" value="Да">
        </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/products/detail.html
{% extends 'dashboard/base.html' %}

{% block styles %}
    <style>
        form label {
            color: black !important;
        }

        form * {
            margin: 0 auto;
            margin-bottom: 10px;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container p-2 content-block">
        <a href="{% url 'products' %}" class="btn btn-primary m-3">Назад</a>
        <a href="{% url 'glasses_delete' pk=product.id %}" class="btn btn-danger m-3">Удалить</a>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    {% if product.img_1 %}
                        {{ form.img_1.label }}
                        <img width="100%" src="{{ product.img_1.url }}" alt="">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    {% if product.img_2 %}
                        {{ form.img_2.label }}
                        <img width="100%" src="{{ product.img_2.url }}" alt="">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    {% if product.img_3 %}
                        {{ form.img_3.label }}
                        <img width="100%" src="{{ product.img_3.url }}" alt="">
                    {% endif %}
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md">
                    {{ form.is_new.label }}
                    {{ form.is_new }}
                </div>
                <div class="col-md">
                    {{ form.is_leader.label }}
                    {{ form.is_leader }}
                </div>
                <div class="col-md">
                    {{ form.is_discount.label }}
                    {{ form.is_discount }}
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    {{ form.title.label }}
                    {{ form.title }}
                </div>
                <div class="col-md">
                    {{ form.price.label }}
                    {{ form.price }}
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    {{ form.cat.label }}
                    {{ form.cat }}
                </div>
                <div class="col-md">
                    {{ form.subcat.label }}
                    {{ form.subcat }}
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    {{ form.discount.label }}
                    {{ form.discount }}
                </div>

                <div class="col-md">
                    {% if not product.cat == 'frames' %}
                        {{ form.sex.label }}
                        {{ form.sex }}
                    {% else %}
                        {{ form.volume.label }}
                        {{ form.volume }}
                    {% endif %}
                </div>

            </div>
            <div class="row">
                <div class="col-md">
                    {% if product.cat == 'frames' %}
                        {{ form.radius.label }}
                        {{ form.radius }}
                    {% else %}
                        {{ form.brand.label }}
                        {{ form.brand }}
                    {% endif %}
                </div>
                <div class="col-md">
                    {% if product.cat == 'frames' %}
                        {{ form.opt_power.label }}
                        {{ form.opt_power }}
                    {% else %}
                        {{ form.material.label }}
                        {{ form.material }}
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md p-0 text-center">
                    {{ form.img_1.label }}
                    {{ form.img_1 }}
                </div>
                <div class="col-md p-0 text-center">
                    {{ form.img_2.label }}
                    {{ form.img_2 }}
                </div>
            </div>
            <div class="row">
                <div class="col-md p-0 text-center">
                    {{ form.img_3.label }}
                    {{ form.img_3 }}
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    {{ form.description.label }}
                    {{ form.description }}
                </div>
            </div>

            <input type="submit" class="btn btn-success m-3">

        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        $('select[name=cat]').on('change', function () {
            $('select[name=subcat]').empty();
            $('select[name=subcat]').prepend('<option value="Not selected" selected disabled>Выбор</option>');
            if ($("#id_cat option:selected").text() != "{{ product.cat }}") {
                category_id = $('select[name=cat]').val();
                alert(category_id)
                request_url = `http://127.0.0.1:8000/api/products/subcategories/?cat=${category_id}`
                $.ajax({
                    type: "GET",
                    url: request_url,
                    success: function (res) {
                        $('select[name=subcat]').empty();
                        $('select[name=subcat]').append('<option value="1">Выбор..</option>');
                        res.map((row, _) => {
                            $('select[name=subcat]').append('<option value="' + row.id + '">' + row.value + '</option>');
                        })

                    }
                })
            }
        });
    </script>
{% endblock %}

dashboard/templates/dashboard/products/products.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'products/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container p-2 content-block">
        <div class="col-md">
            <h3 class="text-center mb-4">{{ title }}</h3>

            <div class=" p-2 d-flex justify-content-between mb-4">
                <form action="" method="POST" class="row">
                    {% csrf_token %}
                    <div class="col-md">
                        <input type="text" name="search" class="form-control" placeholder="Поиск">
                    </div>
                    <div class="col-md">
                        <input type="submit" value="Искать" class="btn btn-success">
                    </div>
                </form>
                <div>
                    <div class="dropdown">
                        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Создать
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'glasses_create' %}">Очки</a>
                            <a class="dropdown-item" href="{% url 'frame_create' %}">Линзы</a>
                            <a class="dropdown-item" href="{% url 'glasses_create' %}">Outlet</a>
                        </div>
                    </div>
                </div>
            </div>
            <div>

                <table class="table w-100 text-light">
                    <tr>
                        <th>Название</th>
                        <th>Категория</th>
                        <th>Субкатегория</th>
                        <th>Цена</th>
                        <th></th>
                        <th></th>
                    </tr>

                    {% for product in products %}
                        <tr>
                            <td>{{ product.title }}</td>
                            <td>
                                {% if product.cat == 'frames' %}
                                    Линзы
                                {% elif product.cat == 'glasses' %}
                                    Очки
                                {% elif product.cat == 'outlet' %}
                                    Outlet
                                {% endif %}
                            </td>
                            <td>
                                {% if product.subcat_id > 0 %}
                                    {% for subcat in subcategories %}
                                        {% if subcat.id == product.subcat_id %}
                                            {{ subcat.value }}
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    ---
                                {% endif %}
                            </td>
                            <td>
                                {{ product.price }} T
                            </td>
                            <td>
                                {% if product.cat == 'glasses' or product.cat == 'outlet' %}
                                    <a href="{% url 'glasses_detail' pk=product.id %}"
                                       class="btn btn-sm btn-info">Инфо</a>
                                    {% elif product.cat == 'frames' %}
                                    <a href="{% url 'frame_detail' pk=product.id %}"
                                       class="btn btn-sm btn-info">Инфо</a>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'glasses_delete' pk=product.id %}"
                                   class="btn btn-sm btn-danger">Удалить</a>
                            </td>

                        </tr>
                    {% endfor %}
                </table>
                {% if products.has_other_pages %}
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                        {% endif %}
                        {% for i in products.paginator.page_range %}
                            {% if products.number == i %}
                                <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if products.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}